#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common
docker push $TAG_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    ORDERLY_VERSION=$(docker run --rm --entrypoint bash \
                             $TAG_SHA \
                             -c 'echo $ORDERLY_VERSION')
    TAG_VERSION="${PACKAGE_ORG}/${PACKAGE_NAME}:${ORDERLY_VERSION}"
    TAG_LATEST="${PACKAGE_ORG}/${PACKAGE_NAME}:latest"
    docker tag $TAG_SHA $TAG_LATEST
    docker tag $TAG_SHA $TAG_VERSION
    docker push $TAG_LATEST
    docker push $TAG_VERSION
fi
