#!/usr/bin/env bash
set -e

if [ "$#" -neq 1 ]; then
   echo "Usage: republish_vimc <ref>"
   exit 1
fi

REF=$1
docker pull docker.montagu.dide.ic.ac.uk:5000/orderly.server:$REF
docker image tag docker.montagu.dide.ic.ac.uk:5000/orderly.server:$REF \
  vimc/orderly.server:$REF
docker push vimc/orderly.server:$REF
